modLoader="javafml"
loaderVersion="[1,)"
license="GPL-3.0"

[[mods]]
modId="immersivetechnology"
version="1.8.95"
displayName="Immersive Technology"
authors="WoodIsDaniel, tgstyle"
description='''
Immersive Technology for 1.21.1.
Forked.
'''
logoFile="icon.png"

# Dependency for Immersive Engineering
[[dependencies.immersivetechnology]]
modId = "immersiveengineering"
type = "required"
versionRange = "[12.4.0,)"
ordering = "AFTER"
side = "BOTH"

# Dependency for Minecraft
[[dependencies.immersivetechnology]]
modId="minecraft"
type="required"
versionRange="[1.21, 1.21.1)"
ordering="AFTER"
side="BOTH"

# Dependency for Neoforge
[[dependencies.novanillaprogression]]
modId="neoforge"
type="required"
versionRange="[21.0.167,)"
ordering="AFTER"
side="BOTH"